#!/usr/bin/env bash

set -eou pipefail

mkdir -p ~/.config/nvim
mkdir -p ~/.config/alacritty

cp bashrc ~/.bashrc
cp init.lua ~/.config/nvim/init.lua
cp alacritty.toml ~/.config/alacritty/alacritty.toml
